# Generated by Django 2.2.6 on 2020-05-06 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0039_auto_20191129_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepost',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 6, 14, 34, 33, 104918)),
        ),
    ]
