# Generated by Django 2.2.6 on 2020-12-02 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateApp', '0041_auto_20201026_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatepost',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 2, 14, 37, 20, 882082)),
        ),
    ]
